const VIDEOS_DATA = [
    {
        videoTitle: "Talking Tech and AI with Google CEO Sundar Pichai!",
        channelName: "Marques Brownlee",
        videoStacts: "3.4M views · 6 months ago",
        timeStamps: "14:20",
        id: 1,
    },
    {
        videoTitle: "Try Not To Laugh Challenge #9",
        channelName: "Markiplier",
        videoStacts: "19M views · 4 years ago",
        timeStamps: "8:22",
        id: 2,
    },
    {
        videoTitle: "Crazy Tik Toks Taken Moments Before DISASTER",
        channelName: "SSSniperWolf",
        videoStacts: "12M views · 1 year ago",
        timeStamps: "9:13",
        id: 3,
    },
    {
        videoTitle: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
        channelName: "Veritasium",
        videoStacts: "18M views · 4 months ago",
        timeStamps: "22:09",
        id: 4,
    },
    {
        videoTitle: "Kadane's Algorithm to Maximum Sum Subarray Problem",
        channelName: "CS Dojo",
        videoStacts: "519K views · 5 years ago",
        timeStamps: "11:17",
        id: 5,
    },
    {
        videoTitle: "Anything You Can Fit In The Circle I’ll Pay For",
        channelName: "MrBeast",
        videoStacts: "141M views · 1 year ago",
        timeStamps: "19:59",
        id: 6,
    },
    {
        videoTitle: "Why Planes Don't Fly Over Tibet",
        channelName: "RealLifeLore",
        videoStacts: "6.6M views · 1 year ago",
        timeStamps: "10:13",
        id: 7,
    },
    {
        videoTitle: "Inside The World's Biggest Passenger Plane",
        channelName: "Tech Vision",
        videoStacts: "3.7M views · 10 months ago",
        timeStamps: "7:12",
        id: 8,
    },
    {
        videoTitle: "The SECRET to Super Human STRENGTH",
        channelName: "ThenX",
        videoStacts: "20M views · 3 year ago",
        timeStamps: "13:17",
        id: 9,
    },
    {
        videoTitle: "How The World's Largest Cruise Ship Makes 30,000 Meals Every Day",
        channelName: "Business Insider",
        videoStacts: "14M views · 1 year ago",
        timeStamps: "7:53",
        id: 10,
    },
    {
        videoTitle: "Dubai's Crazy Underwater Train and Other Things #Only in Dubai",
        channelName: "Destination Tips",
        videoStacts: "3M views · 1 year ago",
        timeStamps: "4:10",
        id: 11,
    },
    {
        videoTitle: "What would happen if you didn’t drink water? - Mia Nacamulli",
        channelName: "TED-Ed",
        videoStacts: "2M views · 5 years ago",
        timeStamps: "4:51",
        id: 12,
    },
]

export default VIDEOS_DATA